In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler 

In [ ]:
df = pd.read_csv('/content/data.csv')
df.head()

In [ ]:
df = df.drop('id', axis=1)

In [ ]:
df = df.drop('Unnamed: 32', axis=1)

In [ ]:
df.isna().sum()

In [ ]:
from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()
lbl.fit_transform(df.diagnosis)

In [ ]:
df['diagnosis'] = lbl.fit_transform(df.diagnosis)

In [ ]:
df.corr

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
df.info()

In [ ]:
x = df.drop('diagnosis', axis=1)

In [ ]:
y = df['diagnosis'].values

In [ ]:
y

In [ ]:
y = lbl.fit_transform(df.diagnosis)
y

In [ ]:
scaler = StandardScaler()
x_std = scaler.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split  

x_train, x_test, y_train, y_test= train_test_split(x_std, y, test_size= 0.25, random_state=0) 

print('x training shape', x_train.shape)
print('y training shape', y_train.shape)
print('x testing shape', x_test.shape)
print('y testing shape', y_test.shape)

x training shape (426, 30)
y training shape (426,)
x testing shape (143, 30)
y testing shape (143,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier  

knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
knn.fit(x_train, y_train) 

KNeighborsClassifier()

In [ ]:
y_pred = knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)

In [ ]:
cm

array([[89,  1],
       [ 6, 47]])

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

accuracy_score(y_test, y_pred)

0.951048951048951

In [ ]:
X_prime  = np.array(df.iloc[:30, [2,24]])
X_prime

In [ ]:
x_min, x_max = X_prime[:, 0].min() - 1, X_prime[:, 0].max() + 1
y_min, y_max = X_prime[:, 1].min() - 1, X_prime[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
xx, yy

(array([[ 9.38,  9.4 ,  9.42, ..., 28.48, 28.5 , 28.52],
        [ 9.38,  9.4 ,  9.42, ..., 28.48, 28.5 , 28.52],
        [ 9.38,  9.4 ,  9.42, ..., 28.48, 28.5 , 28.52],
        ...,
        [ 9.38,  9.4 ,  9.42, ..., 28.48, 28.5 , 28.52],
        [ 9.38,  9.4 ,  9.42, ..., 28.48, 28.5 , 28.52],
        [ 9.38,  9.4 ,  9.42, ..., 28.48, 28.5 , 28.52]]),
 array([[ 313.9 ,  313.9 ,  313.9 , ...,  313.9 ,  313.9 ,  313.9 ],
        [ 313.92,  313.92,  313.92, ...,  313.92,  313.92,  313.92],
        [ 313.94,  313.94,  313.94, ...,  313.94,  313.94,  313.94],
        ...,
        [2615.94, 2615.94, 2615.94, ..., 2615.94, 2615.94, 2615.94],
        [2615.96, 2615.96, 2615.96, ..., 2615.96, 2615.96, 2615.96],
        [2615.98, 2615.98, 2615.98, ..., 2615.98, 2615.98, 2615.98]]))

In [ ]:
x_min, x_max, y_min, y_max

(9.38, 28.54, 313.9, 2616.0)