In [1]:
import numpy as np
print(np.__version__)

1.19.2


In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [5]:
b = np.array([(1.5, 2, 3), (4,5,6)], dtype=int)
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
b.ndim

2

In [7]:
a.ndim

1

In [8]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=int)
print(c)

[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]]


In [9]:
c.ndim

3

In [11]:
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
o = np.ones((3,4))

In [13]:
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
x = np.arange(10, 25, 2)
x

array([10, 12, 14, 16, 18, 20, 22, 24])

In [17]:
l = np.linspace(0, 2, 9)
l

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
i = np.eye(3)

In [19]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
r = np.random.random((3, 3))
print(r)

[[0.10287279 0.35452912 0.86359636]
 [0.61129372 0.32722269 0.49210195]
 [0.5614923  0.59215003 0.71303122]]


#### Data Types in Numpy
int, float, complex, boolean, string

In [22]:
b.shape

(2, 3)

In [24]:
len(b)

2

In [25]:
c.ndim

3

In [26]:
type(c)

numpy.ndarray

In [27]:
c.dtype

dtype('int32')

In [29]:
t = c.astype(float)

In [30]:
print(t)

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]


In [31]:
t.dtype

dtype('float64')

In [32]:
print(a)
print(a.sum())

[1 2 3 4 5]
15


In [35]:
print(a.max())

5


In [37]:
print(b)
print(b.max(axis=1)) # (axis =1 column) (axis =0 row)

[[1 2 3]
 [4 5 6]]
[3 6]


In [43]:
print(np.median(b))

3.5


In [44]:
print(np.std(b))

1.707825127659933


In [45]:
p = np.array([4, 2, 1, 6, 8, 3, 7])
print(p)

[4 2 1 6 8 3 7]


In [48]:
p.sort()
print(p)

[1 2 3 4 6 7 8]


In [52]:
print(p[:3])

[1 2 3]


In [54]:
b.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
print(b[0:2, 1])

[2 5]


In [65]:
k = np.transpose(b)
k.shape

(3, 2)

In [67]:
print(k)

[[1 4]
 [2 5]
 [3 6]]


In [68]:
v = np.ravel(k)

In [69]:
v

array([1, 4, 2, 5, 3, 6])

In [70]:
v.shape

(6,)

In [74]:
f = v.reshape(2, 3)

In [75]:
print(f)

[[1 4 2]
 [5 3 6]]


In [77]:
h = np.array([0.1, 3.4, 6.], dtype=int)
print(h)

[0 3 6]


In [79]:
m = np.vstack((f, h))
print(m)

[[1 4 2]
 [5 3 6]
 [0 3 6]]
