TA 2 - Implement Decision Trees on Adult Dataset

In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('./dataset/adult.csv')
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [9]:
df.shape

(48842, 15)

In [11]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [12]:
df.describe()

age        fnlwgt  educational-num  capital-gain  \
count  48842.000000  4.884200e+04     48842.000000  48842.000000   
mean      38.643585  1.896641e+05        10.078089   1079.067626   
std       13.710510  1.056040e+05         2.570973   7452.019058   
min       17.000000  1.228500e+04         1.000000      0.000000   
25%       28.000000  1.175505e+05         9.000000      0.000000   
50%       37.000000  1.781445e+05        10.000000      0.000000   
75%       48.000000  2.376420e+05        12.000000      0.000000   
max       90.000000  1.490400e+06        16.000000  99999.000000   

       capital-loss  hours-per-week  
count  48842.000000    48842.000000  
mean      87.502314       40.422382  
std      403.004552       12.391444  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       45.000000  
max     4356.000000       99.000000

In [16]:
uni_class, counts = np.unique(df['workclass'], return_counts = True)
uni_class, counts

(array(['?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private',
        'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay'],
       dtype=object),
 array([ 2799,  1432,  3136,    10, 33906,  1695,  3862,  1981,    21],
       dtype=int64))

In [18]:
pop_class = uni_class[np.argmax(counts, axis = 0)]
pop_class

'Private'

In [20]:
df['workclass'][df['workclass'] == '?'] = pop_class 

C:\Users\adity\AppData\Local\Temp\ipykernel_12700\1703597949.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['workclass'][df['workclass'] == '?'] = pop_class


In [21]:
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18    Private  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [36]:
pop_class = uni_class[np.argmax(counts, axis = 0)]
df['occupation'][df['occupation'] == '?'] = pop_class

C:\Users\adity\AppData\Local\Temp\ipykernel_12700\3056581493.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['occupation'][df['occupation'] == '?'] = pop_class


In [38]:
pop_class = uni_class[np.argmax(counts, axis = 0)]
df['native-country'][df['native-country'] == '?'] = pop_class

C:\Users\adity\AppData\Local\Temp\ipykernel_12700\3375604320.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['native-country'][df['native-country'] == '?'] = pop_class


In [39]:
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18    Private  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4     Prof-specialty    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [42]:
df.education.value_counts()

HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: education, dtype: int64

In [43]:
hs_grad = ['HS-grad','11th','10th','9th','12th']
elementary = ['1st-4th','5th-6th','7th-8th']

df['education'].replace(to_replace = hs_grad,value = 'HS-grad',inplace = True)
df['education'].replace(to_replace = elementary,value = 'elementary_school',inplace = True)

df['education'].value_counts()

HS-grad              20398
Some-college         10878
Bachelors             8025
Masters               2657
Assoc-voc             2061
elementary_school     1711
Assoc-acdm            1601
Prof-school            834
Doctorate              594
Preschool               83
Name: education, dtype: int64

In [44]:
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802       HS-grad                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18    Private  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4     Prof-specialty    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [50]:
df['marital-status'].value_counts()

Married-civ-spouse       22379
Never-married            16117
Divorced                  6633
Separated                 1530
Widowed                   1518
Married-spouse-absent      628
Married-AF-spouse           37
Name: marital-status, dtype: int64

In [51]:
married= ['Married-spouse-absent','Married-civ-spouse','Married-AF-spouse']
separated = ['Separated','Divorced']

df['marital-status'].replace(to_replace = married ,value = 'Married',inplace = True)
df['marital-status'].replace(to_replace = separated,value = 'Separated',inplace = True)

df['marital-status'].value_counts()

Married          23044
Never-married    16117
Separated         8163
Widowed           1518
Name: marital-status, dtype: int64

In [52]:
df.workclass.value_counts()

Private             36705
Self-emp-not-inc     3862
Local-gov            3136
State-gov            1981
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: workclass, dtype: int64

In [53]:
self_employed = ['Self-emp-not-inc','Self-emp-inc']
govt_employees = ['Local-gov','State-gov','Federal-gov']

df['workclass'].replace(to_replace = self_employed ,value = 'Self_employed',inplace = True)
df['workclass'].replace(to_replace = govt_employees,value = 'Govt_employees',inplace = True)

df['workclass'].value_counts()

Private           36705
Govt_employees     6549
Self_employed      5557
Without-pay          21
Never-worked         10
Name: workclass, dtype: int64

In [54]:
df.head()

age       workclass  fnlwgt     education  educational-num marital-status  \
0   25         Private  226802       HS-grad                7  Never-married   
1   38         Private   89814       HS-grad                9        Married   
2   28  Govt_employees  336951    Assoc-acdm               12        Married   
3   44         Private  160323  Some-college               10        Married   
4   18         Private  103497  Some-college               10  Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4     Prof-specialty    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [70]:
del_cols = ['fnlwgt', 'educational-num', 'relationship', 'capital-gain', 'capital-loss']
df.drop(labels = del_cols,axis = 1,inplace = True)

In [71]:
df.head()

age       workclass     education marital-status         occupation   race  \
0   25         Private       HS-grad  Never-married  Machine-op-inspct  Black   
1   38         Private       HS-grad        Married    Farming-fishing  White   
2   28  Govt_employees    Assoc-acdm        Married    Protective-serv  White   
3   44         Private  Some-college        Married  Machine-op-inspct  Black   
4   18         Private  Some-college  Never-married     Prof-specialty  White   

   gender  hours-per-week native-country income  
0    Male              40  United-States  <=50K  
1    Male              50  United-States  <=50K  
2    Male              40  United-States   >50K  
3    Male              40  United-States   >50K  
4  Female              30  United-States  <=50K

In [78]:
df['occupation'].value_counts()

Prof-specialty       8981
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: occupation, dtype: int64

In [68]:
df['hours-per-week'][df['hours-per-week'] < 20].value_counts()

15    623
10    425
16    303
12    247
8     218
18    129
5      95
6      92
4      84
3      59
14     55
2      53
7      45
17     42
13     28
1      27
9      27
11     20
19     19
Name: hours-per-week, dtype: int64

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             48842 non-null  int64 
 1   workclass       48842 non-null  object
 2   education       48842 non-null  object
 3   marital-status  48842 non-null  object
 4   occupation      48842 non-null  object
 5   race            48842 non-null  object
 6   gender          48842 non-null  object
 7   hours-per-week  48842 non-null  int64 
 8   native-country  48842 non-null  object
 9   income          48842 non-null  object
dtypes: int64(2), object(8)
memory usage: 3.7+ MB


In [92]:
X = df.drop(['income'], axis = 1)
y = df['income']

In [93]:
X.head()

age       workclass     education marital-status         occupation   race  \
0   25         Private       HS-grad  Never-married  Machine-op-inspct  Black   
1   38         Private       HS-grad        Married    Farming-fishing  White   
2   28  Govt_employees    Assoc-acdm        Married    Protective-serv  White   
3   44         Private  Some-college        Married  Machine-op-inspct  Black   
4   18         Private  Some-college  Never-married     Prof-specialty  White   

   gender  hours-per-week native-country  
0    Male              40  United-States  
1    Male              50  United-States  
2    Male              40  United-States  
3    Male              40  United-States  
4  Female              30  United-States

In [94]:
y.head()

0    <=50K
1    <=50K
2     >50K
3     >50K
4    <=50K
Name: income, dtype: object

In [102]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X['age'] = le.fit_transform(X.age)
X['workclass'] = le.fit_transform(X.workclass)
X['education'] = le.fit_transform(X.education)
X['marital-status'] = le.fit_transform(X['marital-status'])
X['occupation'] = le.fit_transform(X.occupation)
X['race'] = le.fit_transform(X.race)
X['gender'] = le.fit_transform(X.gender)
X['hours-per-week'] = le.fit_transform(X['hours-per-week'])
X['native-country'] = le.fit_transform(X['native-country'])

In [104]:
X.head()

age  workclass  education  marital-status  occupation  race  gender  \
0    8          2          4               1           6     2       1   
1   21          2          4               0           4     4       1   
2   11          0          0               0          10     4       1   
3   27          2          8               0           6     2       1   
4    1          2          8               1           9     4       0   

   hours-per-week  native-country  
0              39              39  
1              49              39  
2              39              39  
3              39              39  
4              29              39

In [110]:
y

array([0, 0, 1, ..., 0, 0, 1])

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=2)

In [132]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier( criterion= 'entropy', max_depth= 5, min_samples_split= 10)
model.fit(X_train, y_train)

model = DecisionTreeClassifier( criterion= 'gini', max_depth= 5, min_samples_split= 10)
model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_split=10)

In [128]:
y_pred = model.predict(X_test)

In [129]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [131]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[10592,   585],
       [ 2028,  1448]], dtype=int64)

In [126]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89     11177
           1       0.71      0.42      0.53      3476

    accuracy                           0.82     14653
   macro avg       0.78      0.68      0.71     14653
weighted avg       0.81      0.82      0.80     14653

