Suppose the IQ in a certain population is normally distributed with a mean of μ = 100 and standard deviation of σ = 15.

A researcher wants to know if a new drug affects IQ levels, so he recruits 20 patients to try it and records their IQ levels.

The following code shows how to perform a one sample z-test in Python to determine if the new drug causes a significant difference in IQ levels:

In [2]:
# Z-Test

from statsmodels.stats.weightstats import ztest as ztest

#enter IQ levels for 20 patients
data = [88, 92, 94, 94, 96, 97, 97, 97, 99, 99,
        105, 109, 109, 109, 110, 112, 112, 113, 114, 115]

ztest(data,value=110)

(-3.640487595530384, 0.00027212221833431376)

In [3]:
# T-Test 

ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [4]:
import numpy as np
ages_mean=np.mean(ages)
ages_mean

30.34375

In [5]:
sample_size=10
age_sample=np.random.choice(ages,sample_size)

In [6]:
age_sample

array([30, 35, 28, 30, 65, 55, 55, 28, 10, 21])

In [9]:
np.mean(age_sample)

35.7

In [7]:
# Applying T-test
from scipy.stats import ttest_1samp

Below, we can see the pvalue of the given value on the sample_data. (comparing that to the actual mean of the sample we can see how close the value of the ttest is actual to the mean)

In [15]:
ttest_1samp(age_sample, 30)

Ttest_1sampResult(statistic=1.0476611733578904, pvalue=0.32211376802504954)

In [16]:
ttest_1samp(age_sample, 34)

Ttest_1sampResult(statistic=0.31246034994884486, pvalue=0.7618090821119476)

In [17]:
ttest_1samp(age_sample, 35)

Ttest_1sampResult(statistic=0.1286601440965835, pvalue=0.9004558181199233)

In [18]:
ttest_1samp(age_sample, 35.67)

Ttest_1sampResult(statistic=0.005514006175568051, pvalue=0.9957207703261377)

In [19]:
ttest_1samp(age_sample, 39)

Ttest_1sampResult(statistic=-0.606540679312462, pvalue=0.5591427136773532)

Considering another example
Ages of the college students -> (population)
1 class student mean of all the ages

In [20]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)

In [21]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [22]:
classA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [23]:
classA_ages.mean()

46.9

In [28]:
_, p_value = ttest_1samp(classA_ages, school_ages.mean()) 
p_value

1.139027071016194e-13

In [25]:
school_ages.mean()

53.303333333333335

In [29]:
if p_value <= 0.005:
    print("H0 rejected")
else:
    print("H0 accepted")

H0 accepted
