In [1]:
import numpy as np
import pandas as pd 

In [2]:
from sklearn import preprocessing, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, Normalizer, LabelEncoder

In [3]:
X = np.random.random([10, 5])
print(X)

[[0.79121373 0.02896266 0.04081189 0.52629012 0.69076664]
 [0.46807028 0.44557195 0.94866076 0.56149515 0.23561609]
 [0.25516148 0.9522973  0.07071474 0.59478167 0.84009935]
 [0.00124706 0.74470821 0.27412832 0.61146348 0.12558282]
 [0.70954679 0.9300303  0.47729179 0.0177871  0.3917515 ]
 [0.79611302 0.3265084  0.0062614  0.60412399 0.60360711]
 [0.91844615 0.46725594 0.79599142 0.45890174 0.11023164]
 [0.16969527 0.86480204 0.21049195 0.3504885  0.58035751]
 [0.96065062 0.25979443 0.24189632 0.86978208 0.56601472]
 [0.7384421  0.25322794 0.70220668 0.94063085 0.24154881]]


In [4]:
y = np.array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F'])

In [5]:
print(X.shape)

(10, 5)


In [6]:
print(y.shape)

(10,)


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
X_train

array([[0.7384421 , 0.25322794, 0.70220668, 0.94063085, 0.24154881],
       [0.46807028, 0.44557195, 0.94866076, 0.56149515, 0.23561609],
       [0.91844615, 0.46725594, 0.79599142, 0.45890174, 0.11023164],
       [0.16969527, 0.86480204, 0.21049195, 0.3504885 , 0.58035751],
       [0.00124706, 0.74470821, 0.27412832, 0.61146348, 0.12558282],
       [0.79121373, 0.02896266, 0.04081189, 0.52629012, 0.69076664],
       [0.79611302, 0.3265084 , 0.0062614 , 0.60412399, 0.60360711]])

In [9]:
y_train

array(['F', 'M', 'M', 'M', 'F', 'M', 'F'], dtype='<U1')

## Preprocessing
### 1. Standardization

In [10]:
scalar = StandardScaler()

In [11]:
# a = np.array([1, 2, 3, 4, 5, 30, 60])
# a.mean()
# a.std()
# a_std = scalar.fit_transform(a.reshape(-1, 1))
# a_std.mean()
# a_std.std()

In [12]:
Xtrain_std = scalar.fit_transform(X_train)
Xtest_std = scalar.transform(X_test)

print(Xtrain_std.mean(), Xtrain_std.std())

1.9032394707859827e-17 0.9999999999999999


In [13]:
print(Xtrain_std)

[[ 0.56408835 -0.73317421  0.78021283  2.12749945 -0.56225465]
 [-0.26616476 -0.00649469  1.47514305 -0.10332931 -0.58828953]
 [ 1.11684165  0.07542786  1.04465904 -0.70698739 -1.13852146]
 [-1.18240956  1.57736501 -0.60628251 -1.34488929  0.9245594 ]
 [-1.69967742  1.1236481  -0.42684609  0.1906836  -1.07115497]
 [ 0.72613854 -1.58045291 -1.08473189 -0.31047518  1.40907423]
 [ 0.7411832  -0.45631916 -1.18215443  0.14749812  1.02658698]]


In [14]:
enc = LabelEncoder()

y_enc = enc.fit_transform(y_train)
yt_enc = enc.fit_transform(y_test)

In [17]:
print(y_enc)

[0 1 1 1 0 1 0]


In [18]:
print(yt_enc)

[0 0 1]


## Selection of Algorithms
### 1. Supervised Learning Algorithms

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier, MLPRegressor

### 2. Unsupervised Learning Algorithms

In [22]:
from sklearn.cluster import KMeans
# from sklearn.decomposition import pca

### Model Fitting 

In [ ]:
mlp = MLPClassifier()

print(Xtrain_std.shape)
print(y_enc.shape)

mlp.fit(Xtrain_std, y_enc)

(7, 5)
(7,)


C:\Users\adity\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [ ]:
print(mlp.score(Xtrain_std, y_enc))

1.0


In [ ]:
mlp_score = mlp.score(Xtest_std, yt_enc)
print(mlp_score)

1.0


In [ ]:
y_pred = mlp.predict(X_test)
print(y_pred)

[0 0 1]


In [ ]:
cm = confusion_matrix(yt_enc, y_pred)
print(cm)

[[2 0]
 [0 1]]


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
cr = classification_report(yt_enc, y_pred)

print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [ ]:
print(4%7+6)

10
