In [1]:
import numpy as np
import pandas as pd 

In [2]:
from sklearn import preprocessing, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, Normalizer, LabelEncoder

In [3]:
X = np.random.random([10, 5])
print(X)

[[0.14483025 0.24466529 0.94954983 0.13610518 0.69667024]
 [0.86071414 0.71477733 0.75300556 0.18489286 0.54973102]
 [0.87885898 0.16752706 0.56429798 0.72855161 0.78058551]
 [0.42617001 0.94673863 0.66033117 0.5716003  0.53876859]
 [0.61231072 0.54151314 0.99629633 0.07494345 0.17308212]
 [0.94024883 0.54234917 0.11774905 0.10416571 0.33239131]
 [0.12134193 0.20570651 0.30714144 0.8733644  0.38878678]
 [0.25569627 0.83292342 0.99974889 0.93093918 0.37898578]
 [0.75957328 0.11737091 0.62253861 0.5413248  0.88017337]
 [0.47585621 0.2829341  0.68148293 0.82870107 0.79491156]]


In [4]:
y = np.array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F'])

In [5]:
print(X.shape)

(10, 5)


In [6]:
print(y.shape)

(10,)


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
X_train

array([[0.47585621, 0.2829341 , 0.68148293, 0.82870107, 0.79491156],
       [0.86071414, 0.71477733, 0.75300556, 0.18489286, 0.54973102],
       [0.12134193, 0.20570651, 0.30714144, 0.8733644 , 0.38878678],
       [0.25569627, 0.83292342, 0.99974889, 0.93093918, 0.37898578],
       [0.42617001, 0.94673863, 0.66033117, 0.5716003 , 0.53876859],
       [0.14483025, 0.24466529, 0.94954983, 0.13610518, 0.69667024],
       [0.94024883, 0.54234917, 0.11774905, 0.10416571, 0.33239131]])

In [9]:
y_train

array(['F', 'M', 'M', 'M', 'F', 'M', 'F'], dtype='<U1')

## Preprocessing
### 1. Standardization

In [10]:
scalar = StandardScaler()

In [11]:
# a = np.array([1, 2, 3, 4, 5, 30, 60])
# a.mean()
# a.std()
# a_std = scalar.fit_transform(a.reshape(-1, 1))
# a_std.mean()
# a_std.std()

In [12]:
Xtrain_std = scalar.fit_transform(X_train)
Xtest_std = scalar.transform(X_test)

print(Xtrain_std.mean(), Xtrain_std.std())

-8.881784197001253e-17 1.0


In [13]:
print(Xtrain_std)

[[ 0.04981994 -0.91467625  0.14423694  0.90386466  1.67809036]
 [ 1.31438109  0.63038722  0.38385283 -0.97229749  0.14951376]
 [-1.11503839 -1.19098376 -1.109886    1.03402089 -0.85389218]
 [-0.67357867  1.05309433  1.21049501  1.20180317 -0.91499647]
 [-0.11343829  1.46030628  0.07337407  0.15463107  0.08116851]
 [-1.03786081 -1.0515957   1.04231757 -1.11447275  1.06560543]
 [ 1.57571513  0.01346786 -1.74439042 -1.20754956 -1.20548941]]


In [14]:
enc = LabelEncoder()

y_enc = enc.fit_transform(y_train)
yt_enc = enc.fit_transform(y_test)

## Selection of Algorithms
### 1. Supervised Learning Algorithms

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier, MLPRegressor

### 2. Unsupervised Learning Algorithms

In [16]:
from sklearn.cluster import KMeans
from sklearn.decomposition import pca

C:\Users\adity\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.decomposition.pca module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)


### Model Fitting 

In [17]:
mlp = MLPClassifier()

print(Xtrain_std.shape)
print(y_enc.shape)

mlp.fit(Xtrain_std, y_enc)

(7, 5)
(7,)


C:\Users\adity\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [18]:
print(mlp.score(Xtrain_std, y_enc))

1.0


In [19]:
mlp_score = mlp.score(Xtest_std, yt_enc)
print(mlp_score)

1.0


In [20]:
y_pred = mlp.predict(X_test)
print(y_pred)

[0 0 1]


In [21]:
cm = confusion_matrix(yt_enc, y_pred)
print(cm)

[[2 0]
 [0 1]]


In [22]:
from sklearn.metrics import classification_report


In [23]:
cr = classification_report(yt_enc, y_pred)

print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [24]:
print(4%7+6)

10
