In [1]:
# sklearn
from sklearn import preprocessing,datasets

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
import numpy as np

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
from sklearn.preprocessing import Normalizer

In [7]:
# Dataset creation
x = np.random.random ((10,5))

In [8]:
x

array([[0.10847802, 0.95076234, 0.29593912, 0.10105511, 0.51314569],
       [0.61769847, 0.70339471, 0.58981547, 0.76070347, 0.86354187],
       [0.32414806, 0.9761395 , 0.02765735, 0.10564973, 0.58319378],
       [0.697511  , 0.10573861, 0.43416581, 0.61425406, 0.33535141],
       [0.03288647, 0.89119304, 0.87407141, 0.09765075, 0.71619157],
       [0.84511859, 0.99807656, 0.60286903, 0.66885713, 0.55513709],
       [0.9672113 , 0.50875816, 0.31105545, 0.57352031, 0.91598648],
       [0.86446287, 0.66887119, 0.66538463, 0.53042111, 0.44080545],
       [0.59533558, 0.13022676, 0.20688154, 0.1919064 , 0.87085181],
       [0.82943304, 0.76516079, 0.66334364, 0.05958744, 0.66279596]])

In [9]:
y = np.array(['m','m','f','f','m','f','m','m','f','f'])

In [10]:
y

array(['m', 'm', 'f', 'f', 'm', 'f', 'm', 'm', 'f', 'f'], dtype='<U1')

In [11]:
x [x<0.7] = 0

In [12]:
x

array([[0.        , 0.95076234, 0.        , 0.        , 0.        ],
       [0.        , 0.70339471, 0.        , 0.76070347, 0.86354187],
       [0.        , 0.9761395 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.89119304, 0.87407141, 0.        , 0.71619157],
       [0.84511859, 0.99807656, 0.        , 0.        , 0.        ],
       [0.9672113 , 0.        , 0.        , 0.        , 0.91598648],
       [0.86446287, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.87085181],
       [0.82943304, 0.76516079, 0.        , 0.        , 0.        ]])

In [13]:
#data split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state=0)

In [14]:
print("x Training data shape:", x_train.shape)
print("x Training data shape:", x_test.shape)
print("y Training data shape:", y_train.shape)
print("y Training data shape:", y_test.shape)

x Training data shape: (7, 5)
x Training data shape: (3, 5)
y Training data shape: (7,)
y Training data shape: (3,)


In [15]:
#Data preprocessing
#1. Standardization
# here we want to impport a lib so add it above for simplicity 
# from sklearn.preprocessing import StandardScaler

In [16]:
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)

In [17]:
print(b)
print(b.mean())
print(b.std())

[[1.5 2.  3. ]
 [4.  5.  6. ]]
3.5833333333333335
1.5920810978785667


In [18]:
scaler = StandardScaler()

In [19]:
b_std = scaler.fit_transform(b)
print (b_std)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [20]:
print(b_std.mean())
print(b_std.std())

0.0
1.0


In [21]:
std_X = scaler.fit_transform(x_train)

In [22]:
std_xtest = scaler.transform(x_test)

In [23]:
print(std_X)
print(std_xtest)
print(std_X.mean())

[[ 0.7540861   0.63974413  0.         -0.40824829 -0.63207136]
 [-1.14966076  0.49707278  0.          2.44948974  1.51498104]
 [ 1.0703201  -1.1276747   0.         -0.40824829  1.64537577]
 [ 0.83448792 -1.1276747   0.         -0.40824829 -0.63207136]
 [-1.14966076 -1.1276747   0.         -0.40824829 -0.63207136]
 [-1.14966076  1.06845884  0.         -0.40824829 -0.63207136]
 [ 0.79008817  1.17774834  0.         -0.40824829 -0.63207136]]
[[-1.14966076  1.12707667  0.         -0.40824829 -0.63207136]
 [-1.14966076 -1.1276747   0.         -0.40824829  1.53315597]
 [-1.14966076  0.93086173  0.87407141 -0.40824829  1.14861917]]
-8.564577618536922e-17


In [24]:
#2. Normalization
#from sklearn.preprocessing import Normalizer

In [25]:
norm = Normalizer()

In [26]:
norm_X = norm.fit_transform(x_train)
norm_xtest = norm.transform(x_test)

In [27]:
# Labelencoder or one-hot encode
from sklearn.preprocessing import LabelEncoder
lbn = LabelEncoder()
print(y)
y_enc = lbn.fit_transform(y)
print(y_enc)


['m' 'm' 'f' 'f' 'm' 'f' 'm' 'm' 'f' 'f']
[1 1 0 0 1 0 1 1 0 0]


In [28]:
# Algorithms
#Linear regression

from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.svm import SVC, SVR
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import *

In [29]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [30]:
#2. Unsupervised
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
#---------------

In [31]:
# Model Fitting
mlp = MLPClassifier()
mlp.fit(std_X,y_train)

C:\Users\adity\anaconda3\envs\ml\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [32]:
#prediction
y_pred = mlp.predict(std_xtest)

In [33]:
print(y_pred)

['m' 'm' 'm']
