In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])   #array 

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
b = np.array([(1.4,2,3.3), (23.4,34,12)], dtype = float)

In [6]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [7]:
c = np.array([[(1,2,3), (23,34,12)],[(1,4,2), (2,33,12)]],dtype = float)

In [8]:
c

array([[[ 1.,  2.,  3.],
        [23., 34., 12.]],

       [[ 1.,  4.,  2.],
        [ 2., 33., 12.]]])

In [9]:
c.ndim  # shows number of dimension (ndim)

3

In [10]:
z = np.zeros([3,4],dtype = int)  # to create 0's array

In [11]:
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
x = np.ones((4,3,2))  

In [13]:
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
x.ndim

3

In [15]:
x1 = np.ones((4,3,))  

In [16]:
x1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
x1.ndim

2

In [18]:
 d = np.arange(10,23,7,)

In [19]:
d

array([10, 17])

In [20]:
lp = np.linspace(0,2,9)

In [21]:
lp

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
f = np.eye(2)

In [23]:
f

array([[1., 0.],
       [0., 1.]])

In [24]:
f1 = np.eye(3)

In [25]:
f1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
e = np.empty((3,2))  #random variables #
e

array([[ 1.4,  2. ],
       [ 3.3, 23.4],
       [34. , 12. ]])

In [27]:
r = np.random.random([2,2])
r

array([[0.33639255, 0.75447807],
       [0.1824699 , 0.69661683]])

In [28]:
d.shape



(2,)

In [29]:
d.size

2

In [30]:
len(d)

2

In [31]:
d.dtype

dtype('int32')

In [32]:
e.dtype

dtype('float64')

In [33]:
e.dtype.name

'float64'

In [34]:
e1 = e.astype(int)  #e1 is to store the new data type of 'e', where e was previously float

In [35]:
e1.dtype.name

'int32'

In [36]:
np.sum(d)

27

In [37]:
np.min(d)

10

In [38]:
np.max(d)

17

In [39]:
e

array([[ 1.4,  2. ],
       [ 3.3, 23.4],
       [34. , 12. ]])

In [40]:
np.max(e, axis = 0)  # column wise max value of each column

array([34. , 23.4])

In [41]:
np.max(e, axis = 1) # Row wise

array([ 2. , 23.4, 34. ])

In [42]:
np.mean(e)

12.683333333333332

In [43]:
np.median(e)

7.65

In [44]:
np.std(e)

12.24206091945125

In [45]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [46]:

b.cumsum(axis=1)

array([[ 1.4,  3.4,  6.7],
       [23.4, 57.4, 69.4]])

In [47]:
np.mean(a)

3.0

In [48]:
a.mean()

3.0

In [49]:
np.corrcoef(b)

array([[ 1.        , -0.68468735],
       [-0.68468735,  1.        ]])

In [50]:
e.sort(axis = 0)

In [51]:
e

array([[ 1.4,  2. ],
       [ 3.3, 12. ],
       [34. , 23.4]])

In [52]:
np.sort(b, axis = 0)

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [53]:
a

array([1, 2, 3, 4, 5])

In [54]:
a[0:2]

array([1, 2])

In [55]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [56]:
b[0:1,1]

array([2.])

In [57]:
b[:1]

array([[1.4, 2. , 3.3]])

In [58]:
b1 = np.transpose(b)

In [59]:
b1

array([[ 1.4, 23.4],
       [ 2. , 34. ],
       [ 3.3, 12. ]])

In [60]:
c

array([[[ 1.,  2.,  3.],
        [23., 34., 12.]],

       [[ 1.,  4.,  2.],
        [ 2., 33., 12.]]])

In [61]:
c1 = c.ravel()

In [62]:
c1

array([ 1.,  2.,  3., 23., 34., 12.,  1.,  4.,  2.,  2., 33., 12.])

In [63]:
b.shape

(2, 3)

In [64]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [65]:
b.reshape(3,2)

array([[ 1.4,  2. ],
       [ 3.3, 23.4],
       [34. , 12. ]])

In [66]:
b.reshape(6,1)

array([[ 1.4],
       [ 2. ],
       [ 3.3],
       [23.4],
       [34. ],
       [12. ]])

In [68]:
print(a)
print(b)

[1 2 3 4 5]
[[ 1.4  2.   3.3]
 [23.4 34.  12. ]]


In [69]:
a2 = (1,2,3)

In [70]:
combine = np.vstack((a2,b))

In [71]:
combine

array([[ 1. ,  2. ,  3. ],
       [ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])